---
- name: EOS Config
  hosts: pynet-sw5
 
  tasks:
    - name: Add Static Routes
      eos_config:
         provider: "{{eapi_creds}}"
         lines:
            - ip route 1.1.1.1/32 {{default_gw}}
            - ip route 1.1.2.1/32 {{default_gw}}
            - ip route 1.1.3.1/32 {{default_gw}}
            - ip route 1.1.4.1/32 {{default_gw}}
